# Generated by Django 6.0.1 on 2026-01-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('post_like', 'Post Like'), ('post_comment', 'Post Comment'), ('post_tag', 'Post Tag')], max_length=20),
        ),
    ]
